name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        gnucobol_version: [2.2,3.1,3.1.1,3.1.2]
        include:
          - version: gnu-cobol-1.1
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push gnucobol version ${{ matrix.gnucobol_version }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          gnucobol_version: ${{ matrix.gnucobol_version }}
